### ISSUE TITLE
BUG: Mission Tracker mission order changes after relog

### ISSUE THREAD

**Issue by SimonNitzsche** [DarkflameUniverse/DarkflameServer#360]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

It looks like after a relog the order of missions on the mission tracker (the bubble in the top center of the UI) seems to change.

### Reproduction steps

- Start some missions
- Look at the order
- Relog

### Expected Behavior

The order should stay

### Environment

Ask Jett (Oog)

**Comment by Jettford** [comment]
> Ask Jett (Oog)

Ubuntu Server 20.04

**Comment by Xiphoseer** [comment]
My guess is, the problem is that the mission component uses a `std::unordered_map` defined in https://github.com/DarkflameUniverse/DarkflameServer/blob/77826c8691bd798471fea9aadd78cfe829397ffc/dGame/dComponents/MissionComponent.h#L174 to store the missions for the user while the UI probably appends them to a list, so the ordering information is never stored right now.

So it could be that the order of nodes in the character XML is implicitly important. The answer is probably something like https://stackoverflow.com/questions/1098175/a-stdmap-that-keep-track-of-the-order-of-insertion, and to make sure that the order does round-trip through the XML serialization as well.

**Comment by EmosewaMC** [comment]
> My guess is, the problem is that the mission component uses a `std::unordered_map` defined in
> 
> https://github.com/DarkflameUniverse/DarkflameServer/blob/77826c8691bd798471fea9aadd78cfe829397ffc/dGame/dComponents/MissionComponent.h#L174
> 
> to store the missions for the user while the UI probably appends them to a list, so the ordering information is never stored right now.
> So it could be that the order of nodes in the character XML is implicitly important. The answer is probably something like https://stackoverflow.com/questions/1098175/a-stdmap-that-keep-track-of-the-order-of-insertion, and to make sure that the order does round-trip through the XML serialization as well.
> 
> EDIT: Do we know from live that the order never changed?

Yes. Just watched a video today of Jamie relogging and the order did not change.
