### ISSUE TITLE
Tracking Issue: Missing Scripts

### ISSUE THREAD

**Issue by aronwk-aaron** [DarkflameUniverse/DarkflameServer#746]
This issue is to track missing scripts reported by the server per world.
This list is non-exhaustive, and will contain duplicates.
This will help to serve as a guide as to what scripts aren't implemented in general.

Venture Explorer
 - [ ] `scripts\ai\AG\L_AG_SHIP_SHAKE.lua` Currently lumped into `AgSpaceStuff` Split out?

Return to the Venture Explorer
 - [x] `scripts\ai\FV\L_FV_MAELSTROM_GEYSER.lua` #748 

Avant Gardens
 - [ ] `scripts\zone\AG\L_ZONE_AG.lua`
 - [ ] `scripts\02_server\Map\General\L_ENEMY_CLEAR_THREAT.lua`
 - [x] `scripts\02_server\Map\General\L_QB_SPAWNER.lua` #761 
 - [x] `scripts\ai\AG\L_AG_QB_Wall.lua` #761 
 - [ ] `scripts\ai\AG\L_AG_SENTINEL_GUARD.lua`

Avant Gardens Survival
 - [ ] `scripts\ai\AG\L_AG_SPIDER_BOSS_MESSAGE.lua`

Nimbus Station
 - [ ] `scripts\zone\NS\L_ZONE_NS.lua`
 - [ ] `scripts\ai\GF\L_GF_RACE_INSTANCER.lua` Needed to add double click and dragging functionality to racing
 - [ ] `scripts\ai\AG\CONCERT_STAGE.lua`
 - [ ] `scripts\ai\NS\L_NS_CAR_MODULAR_BUILD.lua`

Pet Cove
 - [x] `scripts\ai\MINIGAME\Objects\MINIGAME_BLUE_MARK.lua` #1349
 - [ ] `scripts\ai\PETS\PET_BLOCKER.lua`
 - [ ] `scripts\ai\PETS\PET_FLEA_MISSION.lua`
 - [ ] `scripts\ai\ACT\L_ACT_PET_INSTANCE_EXIT.lua`

Nimbus Station Shooting Gallery
 - [ ] `scripts\ai\MINIGAME\SG_NS\L_ZONE_SG_NS_SERVER.lua`
 - [ ] `scripts\ai\MINIGAME\SG_GF\SERVER\SG_CANNON_INSTANCE_ACTOR.lua`
 - [ ] `scripts\02_server\Minigame\SG\L_AG_SG_CANNON_SERVER.lua`

Vertigo Loop
 - [ ] `scripts\ai\RACING\TRACK_NS\NS_RACE_SERVER.lua`
 - [x] `scripts\ai\MINIGAME\Objects\MINIGAME_BLUE_MARK.lua` #1349

Gnarled Forest
 - [ ] `scripts\ai\GF\L_ZONE_GF.lua`
 - [ ] `scripts\ai\GF\L_GF_RACE_INSTANCER.lua` See above comment
 - [x] `scripts\ai\GF\L_GF_PARROT_CRASH.lua` #752 
 - [x] `scripts\ai\MINIGAME\Objects\MINIGAME_BLUE_MARK.lua` #1349 
 - [x] `scripts\ai\GF\L_GF_MAELSTROM_GEYSER.lua` #749 
 - [x] `scripts\ai\GF\L_PIRATE_REP.lua` #751 
 - [ ] `scripts\ai\MINIGAME\SG_GF\SERVER\SG_CANNON_INSTANCE_ACTOR.lua`
 - [ ] `scripts\ai\AG\L_AG_ZONE_PLAYER.lua`

Cannon Cove Shooting Gallery
 - [ ] `scripts\ai\MINIGAME\SG_GF\SERVER\SG_CANNON_INSTANCE_EFFECT.lua`
 - [ ] `scripts\ai\MINIGAME\SG_GF\SERVER\SG_CANNON_INSTANCE_ACTOR.lua`

Keelhaul Canyon
 - [x] `scripts\empty.lua` #769 

Forbidden Valley
 - [ ] `scripts\ai\GF\L_GF_RACE_INSTANCER.lua` See above comment
 - [x] `scripts\ai\FV\L_FV_FACILITY_PIPES.lua` #754 
 - [x] `scripts\ai\FV\L_FV_MAELSTROM_GEYSER.lua` #748 

Forbidden Valley Seige
 - [ ] `scripts\ai\MINIGAME\SIEGE\FV_SIEGE_SERVER.lua`
 - [ ] `scripts\ai\MINIGAME\Objects\MINIGAME_BLUE_POINT.lua`
 - [x] `scripts\ai\MINIGAME\Objects\MINIGAME_BLUE_MARK.lua` #1349
 - [ ] `scripts\ai\MINIGAME\Objects\MINIGAME_RED_SPAWN.lua`
 - [ ] `scripts\ai\MINIGAME\Objects\MINIGAME_BLUE_SPAWN.lua`
 - [ ] `scripts\ai\MINIGAME\Objects\MINIGAME_SHARK_PLAYER_DEATH_TRIGGER.lua`
 - [ ] `scripts\ai\AG\L_AG_SURVIVAL_SCENARIO_EXIT.lua`
 - [ ] `scripts\ai\MINIGAME\SIEGE\OBJECTS\RETURN_OBJECT_SERVER.lua`
 - [ ] `scripts\ai\MINIGAME\SIEGE\OBJECTS\DEFENDER_GATE_SERVER.lua`
 - [ ] `scripts\ai\MINIGAME\SIEGE\OBJECTS\DEFENDER_MINE_SERVER.lua`
 - [ ] `scripts\ai\MINIGAME\SIEGE\OBJECTS\ATTACKER_BOUNCER_SERVER.lua`
 - [x] `scripts\ai\SPEC\L_SPECIAL_SPEED_BUFF_SPAWNER.lua` #1050 
 - [x] `scripts\ai\SPEC\L_SPECIAL_LIFE-POWERUP-SPAWNER.lua` #1050 
 - [x] `scripts\ai\SPEC\L_SPECIAL_ARMOR-POWERUP-SPAWNER.lua` #1050 
 - [x] `scripts\ai\SPEC\L_SPECIAL_IMAGINE-POWERUP-SPAWNER-2PT.lua` #1050 

Forbidden Valley Dragon Battle
 - [ ] `scripts\ai\FV\Dragon_Instance\L_FV_DRAGON_INSTANCE_SERVER.lua`
 - [ ] `scripts\02_server\Enemy\FV\L_FV_DRAGON_RONIN.lua`

Dragonmaw Chasm
 - [ ] `scripts\ai\RACING\TRACK_FV\FV_RACE_SERVER.lua`
 - [x] `scripts\ai\RACING\OBJECTS\FV_RACE_DRAGON_LAP1_SERVER.lua` #1562
 - [x] `scripts\ai\RACING\OBJECTS\FV_RACE_DRAGON_LAP2_SERVER.lua` #1562
 - [x] `scripts\02_server\Map\FV\Racing\RACE_SHIP_LAP_COLUMNS_SERVER.lua` #1562
 - [x] `scripts\ai\MINIGAME\Objects\MINIGAME_BLUE_MARK.lua` #1349
 - [x] `scripts\ai\RACING\OBJECTS\FV_RACE_PILLAR_ABC_SERVER.lua` #1562
 - [x] `scripts\ai\RACING\OBJECTS\FV_RACE_PILLAR_D_SERVER.lua` #1562
 - [x] `scripts\02_server\Map\FV\Racing\FV_RACING_COLUMNS.lua` #1562

Raven Bluff
 - [x] `scripts\ai\GF\L_GF_PARROT_CRASH.lua` #752 

LUP/WBL Station
 - [ ] `scripts\ai\LS\ForceFieldEffect.lua` #750 
 - [ ] `scripts\ai\NP\L_NPC_NP_JETPACK_GUY.lua`
 - [ ] `scripts\ai\GENERAL\L_NPC_GENERIC_MOVEMENT.lua`

Deep Freeze
 - [ ] `scripts\zone\LUPs\DeepFreeze Intro\WBL_Enemy_Beaver.lua`
 - [x] `scripts\ai\WILD\L_LUP_generic_interact.lua`

Robot City
 - [x] `scripts\zone\LUPs\WBL_generic_zone.lua` #766 
 - [ ] `scripts\zone\LUPs\RobotCity Intro\WBL_RCIntro_InfectedCitizen.lua`
 - [ ] `scripts\zone\LUPs\RobotCity Intro\WBL_RCIntro_Seperator.lua`
 - [x] `scripts\zone\LUPs\RobotCity Intro\WBL_RCIntro_RobotCitizenBlue.lua`
 - [ ] `scripts\zone\LUPs\RobotCity Intro\WBL_RCIntro_Robotanist.lua`
 - [ ] `scripts\ai\WILD\L_LUP_generic_interact.lua`
 - [x] `scripts\zone\LUPs\RobotCity Intro\WBL_RCIntro_RobotCitizenYellow.lua`
 - [x] `scripts\zone\LUPs\RobotCity Intro\WBL_RCIntro_RobotCitizenRed.lua`
 - [x] `scripts\zone\LUPs\RobotCity Intro\WBL_RCIntro_RobotCitizenOrange.lua`
 - [x] `scripts\zone\LUPs\RobotCity Intro\WBL_RCIntro_RobotCitizenGreen.lua`

Moonbase
 - [ ] `scripts\zone\LUPs\Moonbase Intro\MOONBASE-INTRO_INTRO_CINEMATIC.lua`
 - [ ] `scripts\zone\LUPs\Moonbase Intro\WBL_Enemy_Grabbler.lua`

Portabello
 - [x] `scripts\zone\LUPs\WBL_generic_zone.lua` #766 
 - [ ] `scripts\zone\LUPs\Portabello Intro\WBL_Frog_Bridge.lua`
 - [ ] `scripts\ai\GENERAL\L_NPC_GENERIC_WANDER_SMALL.lua`
 - [ ] `scripts\ai\YRK\L_YRK_NPC_ON_TIMER.lua`
 - [ ] `scripts\ai\NP\L_NP_DIRTDROP_OBJECT.lua`
 - [ ] `scripts\ai\WILD\L_WILD_GF_FROG.lua`
 - [ ] `scripts\zone\LUPs\Portabello Intro\WBL_Starflies.lua`

LEGO Club
 - [ ] `scripts\ai\LS\ForceFieldEffect.lua` #750 
 - [ ] `scripts\ai\GENERAL\L_NPC_GENERIC_MOVEMENT.lua`
 - [ ] `scripts\ai\NP\L_NPC_NP_JETPACK_GUY.lua`

Crux Prime
 - [ ] `scripts\02_server\Map\General\L_ENEMY_CLEAR_THREAT.lua`
 - [ ] `scripts\02_server\Map\AM\L_SKELETON_SPAWNER_VOLUME.lua`
 - [ ] `scripts\02_server\Objects\L_TURRET.lua`
 - [x] `scripts\02_server\Map\AM\L_WANDERING_VENDOR.lua` #555 
 - [ ] `scripts\ai\NP\L_NPC_NP_OLD_MAN_SHERLAND.lua`

Nexus Tower
 - [x] `scripts\02_server\Map\NT\L_NT_FACTION_SPY_SERVER.lua` #1349
 - [x] `scripts\ai\MINIGAME\Objects\MINIGAME_BLUE_MARK.lua` #1349
 - [x] `scripts\02_server\Map\NT\L_NT_NAOMI_DIRT_SERVER.lua` #1349
 - [x] `scripts\02_server\Map\General\L_FRICTION_VOLUME_SERVER.lua` #1349
 - [x] `scripts\02_server\Map\NT\L_NT_NAOMI_BREADCRUMB_SERVER.lua` #1349 
 - [x] `scripts\02_server\Map\NT\L_NT_PIPE_VISIBILITY_SERVER.lua` #1349

Ninjago Monestary
 - [ ] `scripts\02_server\Map\njhub\L_EARTH_TRANS_PILLARS.lua` Requires Moving Platform Implementation
 - [ ] `scripts\02_server\Map\njhub\L_LIGHTNING_ORB_SERVER.lua`
 - [ ] `scripts\02_server\Map\General\L_SIMPLE_MOVER_SWITCH.lua`
 - [ ] `scripts\02_server\Map\njhub\L_FIRE_TRANS_ROCKS_MANAGER.lua`
 - [ ] `scripts\02_server\Map\njhub\L_FIRE_TRANS_ROCKS.lua`
 - [ ] `scripts\02_server\Map\njhub\L_OLD_MAN_NPC.lua`

Equipment

- [x] `scripts\equipmenttriggers\shardarmor.lua`
- [ ] `scripts\equipmenttriggers\obyxshardpack.lua`
- [ ] `scripts\equipmenttriggers\rubyshardpack.lua`
- [x] `scripts\equipmenttriggers\coulbackpack.lua`
- [ ] `scripts\equipmenttriggers\L_TRIAL_FACTION_ARMOR_SERVER.lua`
- [ ] `scripts\equipmenttriggers\ImaginationBackPack.lua`

**Comment by EmosewaMC** [comment]
`scripts\empty.lua` is just an invalid script.

**Comment by aronwk-aaron** [comment]
I will say I just mindlessly enabled debug, loaded each world, and then yoinked the logs lol

**Comment by EmosewaMC** [comment]
`scripts\02_server\Map\NT\L_NT_NAOMI_BREADCRUMB_SERVER.lua` its possible this will fix #363

**Comment by EmosewaMC** [comment]
`scripts\02_server\Map\General\L_ENEMY_CLEAR_THREAT.lua` is duplicated

**Comment by jadebenn** [comment]
Should be updated with the NT scripts I think
